### ISSUE TITLE
`neovim` asynchonous support

### ISSUE THREAD

**Issue by DerWeh** [devjoe/vim-codequery#16]
Running your script from `neovim` requires `Dispatch`. Could you support `neovim`'s native asynchronous feature?

**Comment by devjoe** [comment]
(Sorry for late response)

Let me think about it ...

**Comment by johnzeng** [comment]
+1 for this issue

**Comment by syslot** [comment]
One more for this issue.
The main conflict is the `job control api` are different between neovim and vim

**Comment by jaresty** [comment]
I think this issue I just opened is related to the last comment: https://github.com/devjoe/vim-codequery/issues/24

**Comment by johnzeng** [comment]
I have fixed it on my fork... I think I can open a PR.

**Comment by johnzeng** [comment]
OK, I think I am not going to open a PR because I have removed scripts related to menu because I am not using them and I don't wanna install a plugin related to the menu. 

But you can fix this issue by my commits:

[update async settting](https://github.com/devjoe/vim-codequery/commit/92ef4d13fe4b67c7d85c0b7855cb45c8b9884344)

[bug fix for nvim](https://github.com/devjoe/vim-codequery/commit/c993a48a600d030b2a13547424cc3800fbc053d1)

[allow to run async build db](https://github.com/devjoe/vim-codequery/commit/3fa61d4508fb2a48dc3fb12479a358d59a2cbfd3)

**Comment by devjoe** [comment]
Thank you guys @johnzeng @syslot @DerWeh @jaresty.

Now v0.9.2 is released. It should work for NeoVim by default.
(may still need to implement async search)
